In [1]:
import torch

In [2]:
x = torch.empty(5,3)
print(x)

tensor([[5.6719e-11, 7.3471e+28, 2.6383e+23],
        [2.7376e+20, 1.8040e+28, 1.8750e-19],
        [7.3909e+22, 2.4176e-12, 2.6209e+20],
        [4.1641e+12, 8.9625e-01, 7.9309e+34],
        [7.9439e+08, 3.2604e-12, 7.3113e+34]])


In [4]:
x = torch.rand(5,3)
print(x)

tensor([[0.3158, 0.7657, 0.6278],
        [0.7836, 0.0302, 0.4103],
        [0.3268, 0.6918, 0.5320],
        [0.1234, 0.4434, 0.5901],
        [0.7844, 0.4438, 0.4145]])


In [16]:
x = torch.zeros(5,3,dtype=torch.float)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [6]:
# 直接构造一个张量
torch.tensor([5.5,3])

tensor([5.5000, 3.0000])

In [12]:
# 利用已有的张量的shape构建新的张量
x = x.new_ones(5,4,dtype = torch.float)
print(x)
x = torch.randn_like(x,dtype = torch.float)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[-1.3818,  0.8586,  0.8391,  1.5994],
        [ 0.2063, -0.3622, -0.4327, -0.3489],
        [ 0.7277, -0.9178, -0.7043,  1.9808],
        [-0.6967,  0.1376,  1.8739,  0.2440],
        [ 0.7988, -0.5926,  0.6904, -0.6370]])


In [24]:
print(x.size())

torch.Size([5, 3])


In [32]:
y = torch.rand(5,3,dtype = torch.float)
y =  x - y
y

tensor([[-0.2287, -0.7497, -0.1797],
        [-0.0510, -0.4959, -0.8975],
        [-0.9554, -0.5163, -0.4220],
        [-0.5823, -0.7286, -0.9964],
        [-0.4556, -0.3623, -0.8184]])

In [34]:
x = torch.randn(3,3)
x

tensor([[-0.2833, -0.2523,  0.2989],
        [-1.4744,  0.5072, -0.6139],
        [-0.2076,  1.1081, -0.9442]])

In [46]:
x = x.view(9)

In [54]:
x = torch.rand(2,3,dtype = torch.float)
y = torch.rand_like(x,dtype = torch.float)
print(x)
print(y)

tensor([[0.9514, 0.3975, 0.3291],
        [0.7604, 0.0752, 0.3696]])
tensor([[0.1716, 0.3865, 0.1762],
        [0.4926, 0.4041, 0.2064]])


In [57]:
torch.cat((x,y),0)

tensor([[0.9514, 0.3975, 0.3291],
        [0.7604, 0.0752, 0.3696],
        [0.1716, 0.3865, 0.1762],
        [0.4926, 0.4041, 0.2064]])

In [60]:
z = torch.cat((x,y),1)
z

tensor([[0.9514, 0.3975, 0.3291, 0.1716, 0.3865, 0.1762],
        [0.7604, 0.0752, 0.3696, 0.4926, 0.4041, 0.2064]])

In [67]:
z.chunk(chunks=3,dim = 1)

(tensor([[0.9514, 0.3975],
         [0.7604, 0.0752]]), tensor([[0.3291, 0.1716],
         [0.3696, 0.4926]]), tensor([[0.3865, 0.1762],
         [0.4041, 0.2064]]))

In [68]:
x

tensor([[0.9514, 0.3975, 0.3291],
        [0.7604, 0.0752, 0.3696]])

In [69]:
x.clamp(0.3,0.7)

tensor([[0.7000, 0.3975, 0.3291],
        [0.7000, 0.3000, 0.3696]])

In [74]:
x.topk(1)

torch.return_types.topk(
values=tensor([[0.9514],
        [0.7604]]),
indices=tensor([[0],
        [0]]))

In [75]:
x.flatten()

tensor([0.9514, 0.3975, 0.3291, 0.7604, 0.0752, 0.3696])

In [76]:
x.numel()

6

In [77]:
x = torch.rand(10)
y = torch.rand(10)
print(x,y)

tensor([0.9229, 0.3806, 0.0809, 0.5863, 0.9223, 0.5975, 0.8794, 0.5078, 0.3689,
        0.3638]) tensor([0.4918, 0.0514, 0.0298, 0.3572, 0.8785, 0.2352, 0.3665, 0.4019, 0.5137,
        0.3477])


In [81]:
torch.stack((x,y),dim=0)

tensor([[0.9229, 0.3806, 0.0809, 0.5863, 0.9223, 0.5975, 0.8794, 0.5078, 0.3689,
         0.3638],
        [0.4918, 0.0514, 0.0298, 0.3572, 0.8785, 0.2352, 0.3665, 0.4019, 0.5137,
         0.3477]])

In [82]:
torch.cat((x,y),dim = 0)

tensor([0.9229, 0.3806, 0.0809, 0.5863, 0.9223, 0.5975, 0.8794, 0.5078, 0.3689,
        0.3638, 0.4918, 0.0514, 0.0298, 0.3572, 0.8785, 0.2352, 0.3665, 0.4019,
        0.5137, 0.3477])

In [93]:
x.unsqueeze(dim = 1).shape

torch.Size([10, 1])

In [96]:
x = torch.ones(2,2,requires_grad = True)

In [99]:
y = x + 2
z = y + 1
print(x,y,z)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True) tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>) tensor([[4., 4.],
        [4., 4.]], grad_fn=<AddBackward0>)


In [1]:
# 定义一个模型
import torch.nn as nn
import torch.optim as optim
import torch
import torch.nn.functional as F
import pdb

class Net(nn.Module):
    def __init__(self):
        super(Net,self).__init__()
        self.conv1 = nn.Conv2d(1,6,5) # input_channel,ouput_channel,kernel_size
        self.conv2 = nn.Conv2d(6,16,5)
        self.fc1 = nn.Linear(16*5*5,120)
        self.fc2 = nn.Linear(120,84)
        self.fc3 = nn.Linear(84,10)
    def forward(self,x):
        x = F.max_pool2d(F.relu(self.conv1(x)),(2,2))
        x = F.max_pool2d(F.relu(self.conv2(x)),2)
  #      pdb.set_trace()
        x = x.flatten()
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [2]:
# 输入
inputs = torch.rand(1,1,32,32) # batch_size,channel,feature_size
target = torch.rand(1,10,dtype = torch.float)

In [3]:
# 优化器，loss
criterion = nn.MSELoss()
optimizer = optim.SGD(net.parameters(),lr = 0.01)

In [5]:
from tqdm import tqdm
# train
for epoch in tqdm(range(100)):
    output = net(inputs)
    loss = criterion(output,target)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    if epoch % 10 == 0:
        print('epoch {} loss {} '.format(epoch,loss))

  0%|          | 0/100 [00:00<?, ?it/s]/home/zhouwh/anaconda3/lib/python3.7/site-packages/torch/nn/modules/loss.py:431: UserWarning: Using a target size (torch.Size([1, 10])) that is different to the input size (torch.Size([10])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
 28%|██▊       | 28/100 [00:00<00:21,  3.36it/s]

epoch 0 loss 0.3968711495399475 
epoch 10 loss 0.3668432831764221 
epoch 20 loss 0.3382783532142639 
epoch 30 loss 0.3096068203449249 
epoch 40 loss 0.279396653175354 
epoch 50 loss 0.24495340883731842 


 81%|████████  | 81/100 [00:00<00:02,  6.75it/s]

epoch 60 loss 0.19957855343818665 
epoch 70 loss 0.13975022733211517 
epoch 80 loss 0.07448307424783707 
epoch 90 loss 0.028128692880272865 


100%|██████████| 100/100 [00:00<00:00, 114.53it/s]


In [6]:
inputs

tensor([[[[0.1356, 0.2893, 0.5519,  ..., 0.4904, 0.8390, 0.2880],
          [0.8075, 0.1683, 0.0936,  ..., 0.5851, 0.1875, 0.6230],
          [0.8347, 0.7803, 0.0461,  ..., 0.6400, 0.6488, 0.7323],
          ...,
          [0.9875, 0.1924, 0.7698,  ..., 0.4542, 0.5652, 0.4716],
          [0.2793, 0.1737, 0.5364,  ..., 0.5343, 0.2832, 0.4427],
          [0.4320, 0.5593, 0.6524,  ..., 0.3374, 0.6030, 0.6721]]]])

In [7]:
target

tensor([[0.3442, 0.7611, 0.7357, 0.4008, 0.1624, 0.3515, 0.1217, 0.7796, 0.8988,
         0.9917]])

In [8]:
net(inputs)

tensor([0.3398, 0.5458, 0.7528, 0.4875, 0.2332, 0.2651, 0.0874, 0.7303, 0.7390,
        0.9666], grad_fn=<AddBackward0>)

In [9]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset,DataLoader
import torch.nn.functional as F
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

class randomDataset(Dataset):
    def __init__(self,shape_x,shape_y,lens):
        self.shape_x = shape_x 
        self.shape_y = shape_y
        self.lens = lens
        self.data = torch.rand(lens,1,self.shape_x,self.shape_y)
    def __getitem__(self,index):
        return self.data[index]
    def __len__(self):
        return self.lens
rand_loader = DataLoader(randomDataset(24,24,100),batch_size = 5,shuffle = True)

class simpleNet(nn.Module):
    def __init__(self):
        super(simpleNet,self).__init__()
        self.conv1 = nn.Conv2d(1,16,5)
        self.fc1 = nn.Linear(16*20*20,10)
    def forward(self,x):
        x = F.relu(self.conv1(x))
        x = x.view(-1,16*20*20) # 惊为天人的操作
        x = self.fc1(x)
        return x

In [12]:
model = simpleNet()
#if torch.cuda.device_count() > 1:
#    print('let use {} gpus'.format(torch.cuda.device_count()))
#    model = nn.DataParallel(model)
model.to(device)

simpleNet(
  (conv1): Conv2d(1, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=6400, out_features=10, bias=True)
)

In [13]:
from tqdm import tqdm
target = torch.rand(1,10,dtype = torch.float).to(device)
optimizer = optim.SGD(model.parameters(),lr = 0.01)
criterion = nn.MSELoss()
# train
for data in tqdm(rand_loader):
    inputs = data.to(device)
    output = model(inputs)
    print(output.shape)
    loss = criterion(output,target)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    print('loss: {}'.format(loss))

100%|██████████| 20/20 [00:00<00:00, 693.54it/s]

torch.Size([5, 10])
loss: 0.31945642828941345
torch.Size([5, 10])
loss: 0.05370015278458595
torch.Size([5, 10])
loss: 0.014829144813120365
torch.Size([5, 10])
loss: 0.004209326114505529
torch.Size([5, 10])
loss: 0.004121073056012392
torch.Size([5, 10])
loss: 0.005291619338095188
torch.Size([5, 10])
loss: 0.004981996025890112
torch.Size([5, 10])
loss: 0.007103076204657555
torch.Size([5, 10])
loss: 0.008539979346096516
torch.Size([5, 10])
loss: 0.006855757441371679
torch.Size([5, 10])
loss: 0.005385641939938068
torch.Size([5, 10])
loss: 0.00733264209702611
torch.Size([5, 10])
loss: 0.005647116806358099
torch.Size([5, 10])
loss: 0.008674513548612595
torch.Size([5, 10])
loss: 0.005920981988310814
torch.Size([5, 10])
loss: 0.004188993480056524
torch.Size([5, 10])
loss: 0.0066486019641160965
torch.Size([5, 10])
loss: 0.006198296323418617
torch.Size([5, 10])
loss: 0.004707695450633764
torch.Size([5, 10])
loss: 0.004760781303048134


In [20]:
import torch.utils.data as Data
x = torch.rand(10,10)
y = torch.rand(10,1)
# 转换成dataset
datas = Data.TensorDataset(x ,y)

In [21]:
lloader = DataLoader(datas,batch_size=4,shuffle=True)

In [22]:
type(lloader)

torch.utils.data.dataloader.DataLoader

In [23]:
for item in lloader:
    print(item)
    break

[tensor([[0.5239, 0.2366, 0.8512, 0.8190, 0.1067, 0.3709, 0.5687, 0.9362, 0.9355,
         0.2460],
        [0.3404, 0.5247, 0.4257, 0.2317, 0.8499, 0.1017, 0.1456, 0.4393, 0.3741,
         0.5412],
        [0.7588, 0.7238, 0.2314, 0.6618, 0.5616, 0.4977, 0.0041, 0.7055, 0.8686,
         0.0579],
        [0.2623, 0.1401, 0.4428, 0.7162, 0.3891, 0.5980, 0.8248, 0.2911, 0.3581,
         0.6490]]), tensor([[0.5197],
        [0.4676],
        [0.7434],
        [0.1576]])]
